# Generated by Django 5.1.5 on 2025-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("C", "cash"), ("T", "transfer_to_account")],
                default="C",
                max_length=25,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
