# Generated by Django 5.1.5 on 2025-01-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lessons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название урока")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="preview/lessons/", verbose_name="Предварительный просмотр"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                ("link", models.CharField(blank=True, max_length=10000, null=True, verbose_name="Ссылка на видео")),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название курса")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="preview/", verbose_name="Предварительный просмотр"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
                (
                    "lessons",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.lessons",
                        verbose_name="Описание курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
