# Generated by Django 5.1.5 on 2025-01-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="lessons",
        ),
        migrations.AddField(
            model_name="lessons",
            name="courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.courses",
                verbose_name="Курс",
            ),
        ),
    ]
