# Generated by Django 5.1.5 on 2025-01-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_courses_lessons_lessons_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.courses",
                verbose_name="Курс",
            ),
        ),
    ]
