# Generated by Django 5.1.5 on 2025-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="link",
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name="Ссылка на видео"),
        ),
    ]
